- name: Install the latest version of Cockpit
  ansible.builtin.dnf:
    name:
      - cockpit
      - cockpit-storaged
      - cockpit-pcp
    state: latest
  become: true 
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the latest version of Cockpit
  ansible.builtin.apt:
    name:
      - cockpit
      - cockpit-storaged
    state: latest
  become: true 
  when: ansible_facts['os_family']|lower == 'debian'  

- name: Start and enable cockpit
  ansible.builtin.systemd:
    name: cockpit.socket
    state: started
    enabled: true  
  become: true     

- name: Start and enable pmlogger
  ansible.builtin.systemd:
    name: pmlogger.service 
    state: started
    enabled: true  
  become: true 
  