- name: Deploy Grafana Server
  ansible.builtin.include_role:
    name: grafana.grafana.grafana
    apply:
      become: true  

- name: Open Grafana port in firewalld (RedHat family)
  ansible.builtin.firewalld:
    port: 3000/tcp
    permanent: true
    state: enabled
    immediate: true
  become: true      
  when: ansible_facts.os_family == 'RedHat'

- name: Ensure ufw allows Grafana port (Debian family)
  ansible.builtin.command: ufw allow 3000/tcp
  when: ansible_facts.os_family == 'Debian'
  become: true
  register: ufw_allow
  changed_when: ufw_allow.rc == 0

- name: Reload ufw if we changed rules (Debian family)
  ansible.builtin.command: ufw reload
  when: ansible_facts.os_family == 'Debian' and (ufw_allow is defined and ufw_allow.rc == 0)

     