ungrouped:
  hosts:
    dev-control:
    jetsonnano:
    raspberrypi-01:
    raspberrypi-02:   
    raspberrypi-03:    
    raspberrypi-04:
    raspberrypi-05:
    raspberrypi-06:
    raspberrypi-07:
    raspberrypi-08: